# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='members',
            field=models.ManyToManyField(to='attendance.Profile'),
        ),
    ]
