# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170120_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
        ),
    ]
